### ISSUE TITLE
RailsGirls JP として任意団体口座を作る

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#118]
https://github.com/ruby-no-kai/official/issues/161 のうち、RailsGirls 側のアクションをこっちで進めます。

要点は以下のとおり
- Ruby の会の会計上、RailsGirls のスポンサー資金、残金は「預かり金」となっており、これがいつまでもあるのは好ましくない
- そこで RailsGirls JP(仮称)の任意団体口座を作って、そちらに移動する
- スポンサーからの振込先などは今まで通り Ruby の会にお任せする、振り込まれた資金(預り金)は、ずっと置かない程度に任意団体口座に移動する
- 任意団体口座の出し入れは、RailsGirls JP の主要な人たち(誰?)が決裁権限を持って運用する

という感じに進めようと思っています。決める必要があるのは、まず任意団体名ですが、これは "RailsGirls Japan" でよいですかねえ。

**Comment by hsbt** [comment]
4ヶ月越しの登場。MUFJ に確認してきました。

#### 任意団体の口座の作成について
- 基本的には銀行が任意団体そのものを認めれば作成できる
- 代表者の指名、身分証明書、住所、団体の規約(謎の組織ではないという説明等)があれば ok

#### 規約(規定)に必要なもの
- 名称
- 団体の目的、活動内容、その他説明する文章
- 代表者、メンバー、会計の指名

#### ネットバンキング

法人用のサービスを使うので"Windows でのみ利用可能なデバイスとカード"を使う必要があるそうです。

**Comment by hsbt** [comment]
これ、規定をざーっと書いてから、自分は RailsGirls Japan のメンバーである、と思ってる人で校正したのち、口座開設、Ruby の会の預り金を移動、今後の支出については我々が面倒を見ていく、という感じでいかがでしょうか

@yada-ITA も呼んでおこ

**Comment by yada-ITA** [comment]
:eyes: 呼ばれました〜

そして、 進め方もそれで良いと思います！

**Comment by hsbt** [comment]
2014/02/06 に MUFJ に口座を開設してきました

**Comment by springaki** [comment]
ありがとうございます。お疲れ様でした !! :+1:

**Comment by yada-ITA** [comment]
お疲れさまでした！ありがとうございます〜！ :smiley:

**Comment by emorima** [comment]
お疲れ様でした！口座開設ありがとうございます！

**Comment by hsbt** [comment]
@takahashim さんに預り金や昨年下期の未精算な費用を確認中です!
