### ISSUE TITLE
Railsチュートリアルの1.2節「さっそく動作させる」にRails Girls インストール・レシピへのリンクを貼りたい

### ISSUE THREAD

**Issue by yasulab** [railsgirls-jp/railsgirls.jp#128]
お疲れさまです。Railsチュートリアルの安川です。

Railsチュートリアルの読者の方々と何度か対面する機会があり、彼ら/彼女らから「rvm以外(e.g. rbenv, Cloud IDE)のセットアップ方法について学べる参考情報が知りたい」という意見を聞くことが多かったので、Railsチュートリアルの第１章から[Rails Girls インストール・レシピ](http://railsgirls.jp/install/)へのリンクを貼らせて頂けたらと考えているのですが、いかがでしょうか?

ご検討して頂けると幸いです :bow:

**Comment by hsbt** [comment]
もちろん大丈夫です!

**Comment by springaki** [comment]
:+1:

**Comment by yasulab** [comment]
さっそくRailsチュートリアルの第１章にインストール・レシピへのリンクを掲載させて頂きました :) :rocket: 

http://railstutorial.jp/chapters/beginning?version=4.0#rbenv

快諾して頂きありがとうございました !
