### ISSUE TITLE
RailsGirls JP の規約を作る

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#131]
会計をRubyの会から巻き取るにあたって、規約がないと口座作成ができないので作ります。

---
### 団体名

RailsGirls Japan
### 活動内容

RailsGirls Japan は日本における RailsGirls イベントの開催を支援する団体です。RailsGirls イベントとは、以下の項目を満たすイベントです。
- プログラミングのワークショップを開催する
- http://railsgirls.com/ より開催の申し込みを行う
- 参加者は無料でワークショップに参加できる

RailsGirls Japan の支援内容は以下のとおりです。
- 日本で RailsGirls イベントの開催を希望するオーガナイザー(以下、オーガナイザー)に開催に必要な情報共有を行います。
- RailsGirls イベントのWeb サイトの作成、オーガナイザーの作業の補助を行います。
- RailsGirls イベントの開催に必要な資金を、スポンサー費用の回収代行元である日本Rubyの会より譲り受け、イベントごとの会計担当とともに支出の管理を行います。
- オーガナイザーの要請に応じて、地方間のコーチ派遣の交通費の資金援助を行います。交通費は公共交通機関を利用し1万円以上の場合に限り、上限を1万円として実費の半額を補助します。
### メンバー
- @hsbt (会計)
- @yakitorii 
- @emorima 
- @springaki 
- @yada-ITA

**Comment by hsbt** [comment]
メンバーは、地方をまたがって開催支援に行ってくれるオーガナイザーの人にしました。この issue を見て、自分も一員だ!という思いが有る方はご連絡ください(銀行提出の書類にのせるくらいの意味しかないです...)

**Comment by hsbt** [comment]
メンバーの役割として、スポンサー費用の使い方について何らかの意思決定に関わるという部分は重要かもしれない。

**Comment by hsbt** [comment]
@yakitorii @emorima @springaki @yada-ITA こんな内容でよければ会計用の口座作ってこようとおもいますー。この口座、2人まで無料でネットバンクアカウント作れるらしいので、もう1つは西日本で精力的に支援していただいている @springaki さんにお渡しする予定です。

@springaki よろしくお願いします :bow:

**Comment by springaki** [comment]
@hsbt ありがたいです。こちらこそよろしくお願いします !! :smile:

**Comment by yada-ITA** [comment]
@hsbt さん、ありがとうございます！
規約内容、良いと思います！ :smiley:

**Comment by yokolet** [comment]
規約作りご苦労様です。気がついたところ、いくつか言わせてください。

"RailsGirls イベント"の定義はあったほうがいいのではないでしょうか。どのような条件が整っていれいれば、RailsGirls Japan はそのイベントをサポートするのかという内容ですが。

交通費の支給についてですが、"地方間"　というのがよくわからないので、xxx Kmを超えるコーチの派遣については支給するにしたほうがいいんじゃないでしょうか。お金をだすださないでもめないように。

**Comment by hsbt** [comment]
@yokolet アドバイスありがとうございます。確かにその通りなので、草案考えてきます。

**Comment by hsbt** [comment]
ちょっと更新しましたー @yokolet いかがでしょうか?

**Comment by hsbt** [comment]
これで作ってきます!!1

**Comment by yokolet** [comment]
@hsbt わかりやすくなって、いい感じですね。無事、銀行口座を作れるといいですねぇ。
