### ISSUE TITLE
Translate 2013-11-12-openshift.markdown

### ISSUE THREAD

**Issue by yuryu** [railsgirls-jp/railsgirls.jp#134]
Hi,

I'm going to translate 2013-11-12-openshift.markdown into Japanese. The article is updated since it was forked from railsgirls/railsgirls.github.com so I will update the file to the latest as well.

**Comment by hsbt** [comment]
Thanks! I backported latest file from upstream. https://github.com/railsgirls-jp/railsgirls-jp.github.io/blob/7b7bf16a0da3f0c7f92c648c6819c18084a43c38/_posts/2013-11-12-openshift.markdown

**Comment by hsbt** [comment]
https://railsgirls.jp/openshift で翻訳は終わっています。
