### ISSUE TITLE
2013-05-02-install.markdown の翻訳

### ISSUE THREAD

**Issue by kensuke-m** [railsgirls-jp/railsgirls.jp#135]
初めまして．
2013-05-02-install.markdown にところどころ未翻訳の部分があるので翻訳したいと思います．

**Comment by springaki** [comment]
@kensuke-m kyoto 3rd の Miyashitaさん、 よろしくお願いします！

**Comment by eitoball** [comment]
:+1:

**Comment by kensuke-m** [comment]
ありがとうございます．こちらこそよろしくお願いします．
以下のように作業しました．

-----ここから
git clone git@github.com:kensuke-m/railsgirls-jp.github.io.git
cd railsgirls-jp.github.io/
bundle install
bundle exec jekyll serve --watch
見栄えを確認しつつ _posts/2013-05-02-install.markdown を翻訳
git add .
git commit -m "未翻訳だった部分を翻訳しました。"
git push
-----ここまで

これでよろしいのでしょうか？
以前 @springaki さんに口頭でお聞きしたのですが記憶が曖昧で…申し訳ありません．
お手数をおかけしますが，ご教示願えれば幸いです．

**Comment by eitoball** [comment]
@kensuke-m 

プルリクエストを出して下さい。よろしくお願いします。

**Comment by springaki** [comment]
@kensuke-m そこまで合っています :+1: 
その後 GitHub の kensuke-m/railsgirls-jp.github.io.git リポジトリを確認すると Pull Request ボタンが表示されているハズなので、それでプルリクエストを出すことができます。
もし分からなかったら、4/15 の打合せ時にレクチャーしますのでご安心を !! :smile:

**Comment by kensuke-m** [comment]
ありがとうございます！プルリクエストしてみました．
これでこのissueは閉じます．
とても勉強になりました． @springaki さん @eitoball さん，ありがとうございました．

**Comment by springaki** [comment]
@kensuke-m  ありがとうございました !! :+1:
