### ISSUE TITLE
Rails Girls Japan の会計を公開していく

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#138]
スポンサー様からいくら頂いて、イベントごとに何にどれくらい使ったのか、ということを公開していくことでイベントの透明性を確保していきたいなあと思っています。

ひとまず、イベント毎の収支と、年ごとの繰越金を書いていくって感じでどうでしょうか。

**Comment by springaki** [comment]
:+1:

**Comment by springaki** [comment]
https://docs.google.com/spreadsheets/d/1Ww6p8yCsG3aVYJJDjn8bBIds4d0djrowku1ij5dnJRE/edit?usp=sharing
自分用に詳細に管理していたものですが、こんなにも細かくいらない想定でしょうか。本当に収支だけわかればいいのかも？
支出部分もカテゴリ単位で金額がわかればよさそうでしょうか(飲食代なのか文房具・雑貨なのかなどが判れば今後の目安になりそう)。

**Comment by hsbt** [comment]
収入は「スポンサー代」のみで細かい内訳はなし、支出は
- 飲食費
- 文具、雑貨
- 交通費(あれば)
- 会場費(あれば)

の4項目くらいで良さそう感あります。塩尻の収支を出してから、ペライチで作ってみようと思ってます。

**Comment by hsbt** [comment]
サイトの issue ではないので閉じます!
