### ISSUE TITLE
スポンサー向け請求書、領収書をやり取りする ML を告知する

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#140]
請求書を発行するRuby の会と、イベント開催費用の立替を支払う @hsbt と @springaki が入っている ML を railsgirlsjp-invoice@googlegroups.com として作成したので、イベントオーガナイザーはそこに関連書類を投げればあとはなんとかなる、という状態にしたい。

まずは
- スポンサーの請求先といくらか、のリストを作ってくださいねー
- リストはここに投げてくださいねー
- 立て替えた費用については、領収書を用意してもらって、同じ場所に投げてくださいねー

という一連の作業をどこかに可視化して周知するってところかな。

**Comment by springaki** [comment]
まずはこの辺に書いてみるのがいいのでしょうかねー
https://github.com/railsgirls-jp/railsgirls-jp.github.io/wiki/Howtoorganize

**Comment by AyakoMakihara** [comment]
@hsbt @springaki 精算方法について、いくつか質問があります。
- 立て替えた費用の領収書の宛名に指定はありますか？
- 後日、振込で良い場合、請求書発行となりますが、宛名に指定はありますか？
- 領収書と請求書の送付先を教えて下さい。

**Comment by hsbt** [comment]
> 立て替えた費用の領収書の宛名に指定はありますか？
> 後日、振込で良い場合、請求書発行となりますが、宛名に指定はありますか？

特に指定はありませんが、いずれも"RailsGirls Japan" にしていただけるとスムーズです!

> 領収書と請求書の送付先を教えて下さい。

西日本ということで @springaki 宛でお願いします!(住所は教えてくれるはず)

**Comment by springaki** [comment]
> 西日本ということで @springaki 宛でお願いします!(住所は教えてくれるはず)

@AyakoMakihara 
はい ! 私宛に送ってくださいませ ! 住所お伝えします :)

**Comment by AyakoMakihara** [comment]
@hsbt 宛名、了解いたしました :+1:  以下を準備させて頂きます。
- スポンサーの請求先リスト
- 個人立替者への振込先
- 領収書リスト  

@springaki 11/14にお会いした時に住所等を教えて下さい。そう言えば、以前ステッカーを送った先かも？！

**Comment by springaki** [comment]
@AyakoMakihara 了解です :smile:  (以前ステッカー送ってもらった住所です ! )

**Comment by hsbt** [comment]
http://railsgirls.jp/about/ に書いたので閉じる。後でオーガナイザーページにもお知らせしよう
