### ISSUE TITLE
RailsGirls Kobe 1stの立替え費用精算

### ISSUE THREAD

**Issue by springaki** [railsgirls-jp/railsgirls.jp#161]
- [x] Rubyの会からの回収代行待ち
- [x] 立替者への振込
- [x] 遠方コーチへの支援分振込 (今回はなし)

**Comment by shyouhei** [comment]
相互リンク https://github.com/ruby-no-kai/official/issues/198

**Comment by springaki** [comment]
立替者 Aki に 12/24 付で振り込み完了
