### ISSUE TITLE
GitHubへステッカー追加のお願いをする

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/railsgirls.jp#177]
GitHubの年間スポンサーになっていただいた時に、いただいたステッカー(300枚)が、
Matsue 2nd, Kyoto 2nd 分をお渡しすると、残り ４０枚となったので、
GitHubへ 追加でステッカーをお願いできないかを確認してみる。
- [x] GitHubへ追加をお願いできるか確認
- [x] ステッカーの追加枚数決定

**Comment by emorima** [comment]
GitHub Japan の堀江さんにお問い合わせしたところ、オーダーして頂けました!

**Comment by emorima** [comment]
ステッカー届いたら、closeします。

**Comment by springaki** [comment]
:sparkles:

**Comment by AyakoMakihara** [comment]
:smile_cat:

**Comment by emorima** [comment]
:octocat: 500枚ほど(ちゃんと数えたわけではないです) 届きました!

**Comment by springaki** [comment]
:tada:

**Comment by yada-ITA** [comment]
:octocat: :+1:
