### ISSUE TITLE
クックパッドのロゴが古いので更新する

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#180]
@mrkn から問い合わせがあった。

@moro @mrkn 新しいロゴの有りかをお待ちしています!(pull request でも ok)

**Comment by hsbt** [comment]
http://railsgirls.jp/sponsors/

**Comment by mrkn** [comment]
あ、忘れていた。提供します。

**Comment by mrkn** [comment]
これ使ってください http://railsgirls.com/images/cookpad-logo.jpg

**Comment by mrkn** [comment]
LGTM!!

**Comment by emorima** [comment]
@mrkn 確認ありがとうございました！
