### ISSUE TITLE
RubyKaigi の会期中に RailsGirls オーガナイザーふりかえりを開催する

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#185]
@springaki @emorima @yada-ITA @satomicchy @yakitorii (他、RubyKaigi に参加しているオーガナイザーの皆さん)

RailsGirls JP 発足一年目をふりかえって、今年出来たことや出来なかったこと、出来たことをもう少し良くするには?という話をしつつ、来年に向けてって話をしたい

**Comment by yakitorii** [comment]
はーい！ オーガナイザー業がないタイミングを拾いたい（当日どれくらい仕事があるのかよくわかってないのです）

**Comment by emorima** [comment]
了解でーす。

**Comment by yada-ITA** [comment]
はい！ :smiley: 
ただ、初日の参加が無理そう（仕事の都合上。東京にはいます…）なので
その点を考慮して頂けるとありがたいですー。

**Comment by satomicchy** [comment]
めんしょんありがとうございます。
今回のRuby Kaigiは所用で参加できませんので、またどこかで内容をシェアしていただければと思います。
よろしくお願いします。m(_ _)m

**Comment by springaki** [comment]
話をしましょ〜 :+1:

**Comment by kakutani** [comment]
:heart_eyes_cat:

**Comment by chnstz** [comment]
土日にボランティアで参加します！
いにしえのオーガナイザー＆当日どれだけフリーの時間があるか不明ですが、隙を見て潜り込みたいです〜 :bow:

**Comment by hsbt** [comment]
2015 年に開催済みでした!
