### ISSUE TITLE
ActiveRecord::Base -> ApplicationRecord 

### ISSUE THREAD

**Issue by yucao24hours** [railsgirls-jp/railsgirls.jp#208]

**Comment by yucao24hours** [comment]
ていうか Rails 5 になってかわったとこはまとめて PR にしたい。

**Comment by yucao24hours** [comment]
https://github.com/railsgirls-jp/railsgirls-jp.github.io/pull/201 で対応したけど、それの対応もれみたいのがいくつかあるそう。なので気付き次第対応するようにする。とのこと。

**Comment by hsbt** [comment]
こちらも完了しているので close
