### ISSUE TITLE
jp サイトの PIXTA さんのロゴを新しいものに変える

### ISSUE THREAD

**Issue by yucao24hours** [railsgirls-jp/railsgirls.jp#212]
tokyo 6th でスポンサーになっていただいた際に問い合わせたところ、少し前にロゴが変わったとのことで新しいロゴ画像をいただきました。
sponsors ページもこのロゴで差し替えたいです。

**Comment by emorima** [comment]
頑張ります。

**Comment by hsbt** [comment]
新しいロゴ画像をいただけるならシュッとやっておきます。

**Comment by sho-h** [comment]
.comにリンクが張ってあるようなので本家の修正をする必要があるようですが、Tokyo 6thにならって[こちら](http://railsgirls.com/images/tokyo6_pixta_logo.png)に差し替えたらよいです？

**Comment by sho-h** [comment]
ごめんなさい。.com/tokyo 用にコミットしてあるものがありましたね。という事でそれに差し替えたプルリクエストだけ作りました。

**Comment by hsbt** [comment]
これはマージ済み...?

**Comment by sho-h** [comment]
cf45a58 で直したついでにcloseしてたと思ったらコミットを see #xxx にしてたという...orz

マージ済みでした！
