### ISSUE TITLE
「rails_12factor の導入」をしなくても Heroku に push できる

### ISSUE THREAD

**Issue by yucao24hours** [railsgirls-jp/railsgirls.jp#213]
http://railsgirls.jp/heroku

**Comment by igaiga** [comment]
PR出しました
https://github.com/railsgirls-jp/railsgirls-jp.github.io/pull/219

**Comment by hsbt** [comment]
完了しているぽいので閉じます。 　https://github.com/railsgirls/railsgirls.github.com への反映もありがとうございました。
