### ISSUE TITLE
Nitrous Service Shutdown - November 14th

### ISSUE THREAD

**Issue by youchan** [railsgirls-jp/railsgirls.jp#239]
https://community.nitrous.io/posts/nitrous-service-shutdown-november-14th

Nitrous紹介してますよね…

**Comment by hsbt** [comment]
guides.railsgirls.com からは消えているので jp でも消しましょう...! (最近翻訳が追いついてない)

**Comment by emorima** [comment]
Nitrous から Cloud9 の記載に変更済みなので、閉じちゃいます！
