### ISSUE TITLE
RailsGirls Okayama#2の開催報告について

### ISSUE THREAD

**Issue by dai199** [railsgirls-jp/railsgirls.jp#281]
RailsGirls Okayama#2が終了したので、それの開催報告を[日本語のブログ](http://blog.railsgirls.jp/)でしたいのですがどのようにすればよいですか？
こちらで聞くのは適切ではないかもしれませんが、よければ返信いただければ幸いです。

**Comment by dai199** [comment]
写真アップロードについては自己解決しました。
[こちら](http://railsgirls.jp/guide#イベント後)を参考にさせていただきました。ありがとうございます！

**Comment by AyakoMakihara** [comment]
@dai199 解決して良かったです :rabbit:

**Comment by dai199** [comment]
ごめんなさい日本語ブログに関してはどうすればよいでしょうか・・・！

**Comment by emorima** [comment]
@dai199 Tumblr に招待しますので、メールアドレス or Tumblr のアカウントを教えていただけますか?

**Comment by dai199** [comment]
@emorima ありがとうございます！
アカウント名は dai199 です。お願いします！
https://www.tumblr.com/blog/dai199

**Comment by emorima** [comment]
@dai199 すみません。dai199 のアカウントが有効でないとエラーメッセージが出て、招待できないので、メールアドレスを教えて頂けますか？
(FB で直接メッセージで教えて頂くでもOKです)

**Comment by dai199** [comment]
@emorima Facebookでメッセージ送らせていただきました！ありがとうございます！
