### ISSUE TITLE
初回アクセス時に真っ白になる

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#296]
1. Chrome などのプライベートモードでアクセスする
2. 真っ白になる
3. リロードすると表示される

という現象が報告されています。css/js かなんかでブロックしているのか、gh-pages と何か相性が良くないことがおきているのか、という辺りだと思いますが原因まで到達できていません

**Comment by emorima** [comment]
真っ白くならなくなった気がします!

**Comment by emorima** [comment]
こちらその後発生していないので、closeしようと思います!

@snoozer05 対応ありがとうございました!
