### ISSUE TITLE
書籍にRailsの教科書を追加したい。

### ISSUE THREAD

**Issue by sho-h** [railsgirls-jp/railsgirls.jp#310]
#308 を見てRailsの教科書も追加したいなと思いましたので、後でPR出そうかと思っています。個人的には「日本語の書籍のRailsチュートリアルの上」に置きたいと考えています。(まだ見てないけど、以下のような行を追加する想定)

```
* [Railsの教科書](http://igarashikuniaki.net/rails_textbook/) - 基礎的な内容を丁寧に解説しています。ワークショップ中にやった事に近い内容についての解説を含んでおり、Rails5.1に対応。
```

理由は他の書籍だと受けた人たちには難しいのではないかという懸念があるためです。
それらと比べて以下のような点が特に受講者の方たち向けではないかと思っています。

* 基礎的な用語も省略せずに細かく説明してくれる
* 外部リンクがある場合は一次情報に近いものになっており信頼できる
    * 読んだ人がてきとうにぐぐる癖みたいなのが若干かもしれないけど付きにくいんじゃないかとも期待してる
* 読みやすいボリューム

(五十嵐さんに見られるかと思うとこっ恥ずかしい提案だ...)

**Comment by springaki** [comment]
👍 
僕がRailsGirlsでコーチしたり、その後フォローする会でも同様の理由でだいたい "Railsの教科書"をオススメしています。図解が多いのも嬉しいですね。

電子書籍版の情報もある https://github.com/igaiga/rails_textbook に誘導した方がいいのかも？(逆に紛らわしいかな...これくらいの情報なら選んでもらえる気がするのですが)

**Comment by kurotaky** [comment]
👍

**Comment by sho-h** [comment]
@springaki さん、なるほどです。少し上の講義資料もGitHubへのリンクになってるのでそうしてみました。
