### ISSUE TITLE
Rails 5.2 について

### ISSUE THREAD

**Issue by eitoball** [railsgirls-jp/railsgirls.jp#326]
Rails 5.2 では、チュートリアルに関連する機能追加が、いくつか入る予定です。ガイドに以下の2点のような変更を入れたいなぁと思っています。RailsGirlsNagoya04 では Rails 5.2 がリリースされていると思うので、どうするのか半田印したいので、皆様の意見を聞きたいです。

1. Active Storage

* [Carrierwave を使ってサムネイルを作ってみよう](http://railsgirls.jp/thumbnails) を Active Storage を使うように変更・新規作成するのがいいかなぁと思います。いっそのこと、[Rails Girls アプリ・チュートリアル](http://railsgirls.jp/app) の手順の中に入れてしまってもいいかなぁと思いました。参考までに Active Storage については、先日、[こんなブログ記事](http://tech.misoca.jp/entry/2017/12/15/113000) を書きました。

2. Credentials (`config/credentials.yml.enc` や `config/master.key`）

* [GitHubに自分のアプリをPushする](http://railsgirls.jp/github) や [Heroku に Rails アプリをアップ](http://railsgirls.jp/heroku) などのアプリをインターネットに公開する際に関係してくると思います。`secret_key_base` も暗号化される `confi/credentials.yml.enc` に入ります。パブリックなレポジトリを使うためには大事な情報は暗号化されるべきですが、説明とか大変そうなのと、Heroku とかで公開する際に暗号化を解除するキー情報を環境変数に入れるなど手順が増えそうなのを懸念しています。重要なことなどで、チュートリアルの手順に入っていいと思いつつ、credential を使わないようにするのがいいのかなぁとも思っています。

**Comment by hsbt** [comment]
1 については良さそうですね。英語に良い感じにできるなら .com の方にも入れてしまいたい...
2 はインターネットにこれを公開すると大変なことになるので、ファイルには保存しない手を使っているというのも伝えられると良さそうだなあって思いました。

**Comment by igaiga** [comment]
方針賛成です！

そして、Rails5.2と関係ないのですが、Cloud9で新規ユーザー作成ができなくなって、環境構築のところも直していかないとですね・・・。
参考: https://twitter.com/yasulab/status/936475666224001024

本家はcodeenvyというクラウドサービスでガイドが更新されていたのでまずは翻訳してくるのが良さそう。
http://guides.railsgirls.com/install

**Comment by sho-h** [comment]
ちなみに5.2でも現ガイドで動作する感じです？(まだ5.2.1で試した方はおられないかもですが

**Comment by sho-h** [comment]
松江的にぼちぼちタイムアウトですので、2.だけ自分が対応しようかと思います。

**Comment by chiastolite** [comment]
1に関してですが、carrierwaveが無くなってしまうと gem に触れるタイミングがdeviseまで来なくなってしまうので悩ましく思えます。
(一応 herokuならば pg もありますが、gemのありがたさを経験できる感じでもないですよね…)

個人的にはGirls には↓この問いに触れていただきたいと思ってます。

```
Coachより: 何のライブラリがあって、なぜ便利なのかを説明してください。オープンソースソフトウェアが何なのかも説明してください。
```

**Comment by urimaro** [comment]
2023-06-04現在、RailsGirlsで扱っているRailsのバージョンは `7.0.4.2` になりました
現在も以下の状況は変わっていません

1. CarrierWaveを使っている
1. Credentialsについては説明していない

### 「1」について

引き続き、以下の章でCarrierWaveを使っています  

- [8 画像アップロード機能を追加しよう](https://railsgirls.jp/uploads)
- [13 CarrierWave を使って画像をリサイズしよう](https://railsgirls.jp/thumbnails)」

「8」ではコーチにgemの説明を促しています

> Help from the coach
> ライブラリ（Ruby gems）とは何か、なぜ便利なのかを説明しましょう。同様にオープンソースソフトウェアとは何かについて説明をお願いします。

Active Storageについてはgemを説明するときに一緒に説明しても良さそうです
また、コンテンツとして盛り込むのであれば、.jpと.comに提案してもらうのが良さそうです

### 「2」について

Credentialsの説明はしていませんが、「[9 GitHub であなたのアプリのコードを公開しよう](https://railsgirls.jp/github)」で以下のようにPersonal Access Tokenの扱いについて話題にしています

> コードをプッシュするたびにPATが必要になる場合があるかもしれませんが、PATをコンピューターに保存することもできます。このプロセスはOSごとに異なるので、GitHubにコードを継続的にプッシュしたい場合は、コーチに相談してみましょう。

また、コーチに対しても協力を依頼しています

> Help from the coach
> 参加者が望む場合、PATの保存方法の確認と実践に協力してください。参加者のオペレーティングシステムに対応した最新のガイドを見たり、[異なるオペレーティングシステムでPATを保存するためのガイド](https://mgimond.github.io/Colby-summer-git-workshop-2021/authenticating-with-github.html#saving-tokens-in-windows)を参照してください。

このことからCredentialsを話題にする機会は設けられていると思います

---

上記を踏まえて、このissueはcloseしても良いと思いますが、いかがでしょうか？

**Comment by eitoball** [comment]
> 上記を踏まえて、このissueはcloseしても良いと思いますが、いかがでしょうか？

はい、良いと思います。
