### ISSUE TITLE
railsinstaller.org にアクセスできない

### ISSUE THREAD

**Issue by sho-h** [railsgirls-jp/railsgirls.jp#348]
以下のようにアクセスできないようです。インストーラの方はアクセスできましたが、それもいつまでかわからないのと、同じファイルかがよくわかりませんので、今のうちに対策しておいた方がいいかもしれません。

```
$ curl -Lv railsinstaller.org
...
< HTTP/1.1 302 Moved Temporarily
< Server: nginx
< Date: Fri, 11 May 2018 15:34:31 GMT
< Content-Type: text/html
< Content-Length: 154
< Location: http://railsinstaller.org:81/en
< Connection: close
<
* Closing connection 0
* Issue another request to this URL: 'http://railsinstaller.org:81/en'
*   Trying 184.73.230.254...
* TCP_NODELAY set
* Connection failed
* connect to 184.73.230.254 port 81 failed: Operation timed out
* Failed to connect to railsinstaller.org port 81: Operation timed out
* Closing connection 1
curl: (7) Failed to connect to railsinstaller.org port 81: Operation timed out
```

**Comment by sho-h** [comment]
取り急ぎ今のファイルのmd5sumとmtimeだけ見てみました。

```
$ md5sum railsinstaller-3.4.0.exe
93fd96e5c16763c948587e98a4bae087  railsinstaller-3.4.0.exe

$ ls -l railsinstaller-3.4.0.exe
-rw-r--r-- 1 sho-h 112M  9 21  2017 railsinstaller-3.4.0.exe
```

mtimeが以下なので[最後の修正](https://github.com/railsinstaller/railsinstaller-windows/commits/master)の時期とは合ってそうです。

以前五十嵐さんとこの3.4.0のインストーラが使えそうかを話題にした事があるのですが、手元には同じバージョンのファイルがなかったので、md5sumが一致してるかまではわかりませんでした。orz
一致しているようなら、取り急ぎは今あるものを別の所に置いてリンクを張り替えて備えるのがいいかもしれません。

**Comment by hsbt** [comment]
ライセンスが問題ないなら railsgirls.jp においてもよいと思いますが、RubyInstaller2 + `gem i rails` の方がいいかもしれませんね～

**Comment by sho-h** [comment]
[ライセンス](https://github.com/railsinstaller/railsinstaller-windows/blob/master/LICENCE.txt)はMITですかねぇ。一応[opensource.org](https://opensource.org/licenses/MIT)と比較してみましたけど、同じそうでした。でも、tokyo 9thだけ影響ないようにしないとですけど、確かにRubyInstaller2がいいかもしれません。

**Comment by hirokishirai** [comment]
こちらでアクセスできることを確認しました: http://railsinstaller.org/en

**Comment by igaiga** [comment]
@sho-h あわわー。ひとまずTokyo 9thは↑で hirokishirai さんが書いてる /en から辿る感じで良さそう。長期的にはRubyInstaller2良さそうに思います。たしかビルドツールとかも一緒に入れてくれたので、gitだけ追加すれば良いかも。

ちなみに、手元に古いrailsinstaller-3.4.0.exeがあったのでMD5計算して、sho-hさんのやつと一致することを確認しました。

```
$ md5 railsinstaller-3.4.0.exe
MD5 (railsinstaller-3.4.0.exe) = 93fd96e5c16763c948587e98a4bae087
$ ls -l railsinstaller-3.4.0.exe
-rwx------  1 igaiga igaiga  112M  9 24  2017 railsinstaller-3.4.0.exe
```

**Comment by sho-h** [comment]
@igaiga おぉ、railsinstaller-3.4.0.exeが使えそうなのよかったです！これは嬉しいです。RubyInstaller2にビルドツール入ってるなら文句なしですね！恥ずかしながらまだ使った事はなかったのです。
