### ISSUE TITLE
年間スポンサーの永和さんと GitHub さんのロゴが抜けているイベントがある

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#371]
RG JP がサポートしているイベントには掲載するということになっているのを伝え漏れていたので追加します〜。

**Comment by hsbt** [comment]
> 年間スポンサーさんは外部からコーチに来ていただく時に交通費等でお世話になってるんでしたっけ？

はい、その他、開催費用が足りない時の支援に充当しています〜。

**Comment by sho-h** [comment]
了解ですー。

**Comment by hsbt** [comment]
https://github.com/railsgirls/railsgirls/pull/1605 で作ったので後ほどマージ。

**Comment by hsbt** [comment]
@koic 大変失礼しました。2018 年度開催のイベントにはロゴを追加しましたー。

**Comment by koic** [comment]
@hsbt お手数おかけしました。ご対応ありがとうございました 🙏

**Comment by koic** [comment]
@hsbt レビュー不足ですみません。永和システムマネジメントのスポンサーリンク先が Coderwall のサイトになっていたため、`http://coderwall.com/team/eiwa-system-management` から `https://agile.esm.co.jp` に差し替えていただけると助かります。

- http://railsgirls.com/tokyo.html
- http://railsgirls.com/sendai.html
- http://railsgirls.com/okinawa.html

よろしくお願いします。

**Comment by hsbt** [comment]
@koic https://github.com/railsgirls/railsgirls/pull/1639 こんなんでどうでしょうか? 過去の内容をコピったのがその三つ、という内容なので、全部置き換えました。

**Comment by hsbt** [comment]
oh... ひとまず全部書き換えた、って感じなので更新しておきます!

**Comment by koic** [comment]
ありがとうございます！
