### ISSUE TITLE
railsgirls.jp の HTTPS化

### ISSUE THREAD

**Issue by risacan** [railsgirls-jp/railsgirls.jp#377]
いろいろなところでシェアされるサイトなので、HTTPS化しておきたいです。
GitHubにホストしているようなので、比較的かんたんにできるのかな？と思います！
https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

権限いただけるなら、私やります 🙋

**Comment by znz** [comment]
https://rubykansai.github.io/kansai-ruby-community/ が Rails Girls Nara のロゴで mixed content になる (環境によっては表示されない) ので、 https://help.github.com/articles/securing-your-github-pages-site-with-https/ の Enforce HTTPS の設定をして欲しいと思って探してみたら、この issue を見つけたのですが、現状はどんな感じでしょうか?

サイト内に絶対 URL で http を指定しているリンクなどがなければ問題ないと思うのですが。

**Comment by emorima** [comment]
ご連絡遅くなりました。

こちら柴田さんにも確認して頂いたのですが、naked domain(apex domain) のため
httpsにできないようなのです... (DNS Providerに設定して別途設定もらう必要がある)

ドメインをwww.railsgirls.jp とかにすればできるとのことなのですが、
現時点では、そのままが濃厚な状況です。

**Comment by emorima** [comment]
znzさん

こちらのissueなのですが、先程コメントに記載させて頂きましたが、
naked domainのため、対応がちょっと手間がかかり(gh-pagesからherokuに切り替えるとか...)、
現時点ではそのまま...というのが濃厚です。

**Comment by hsbt** [comment]
いつの間にか gh-pages でも apex ドメインで https ができるようになっていたのでやっときました。
