### ISSUE TITLE
/appの1.でbundle installもする

### ISSUE THREAD

**Issue by sho-h** [railsgirls-jp/railsgirls.jp#400]
codenvyではbundle installを実行しないとrails serverが動作しないので、bundle install も必ず行うかコメントを残しておくかする。

**Comment by sho-h** [comment]
僕が対応する場合はしばらく先になりそうですが、現時点で確認だけしておかないと状態が変化するかもしれないので少しだけ確認。

```
$ rails -v
5.0.1
$ rails new sample # この時にbundle install自体は走る
         ...
         run  bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platform
s Bundler is installing for. Bundler is installing for ruby but the dep
endency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add
 those platforms to the bundle, run `bundle lock --add-platform x86-min
gw32 x86-mswin32 x64-mingw32 java`.

$ cd sample
$ rails server # 失敗する
Could not find thread_safe-0.3.6 in any of the sources
Run `bundle install` to install missing gems.

$ rails -v # 少しだけ新しいのが入る
5.0.7

$ bundle install
...
Using minitest 5.11.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
...

$ rails server # 今度は起動する
```

エラーメッセージで検索するに以下の問題のように思うので、Railsが新しくなれば問題は起きなくなりそう。(かなり古いようなので期待できない気はしますね...

* https://github.com/rails/rails/issues/27830

もし対応した場合は10分放置した後など、環境が落とされた後でも問題ないかを確認した方がよい。

**Comment by sho-h** [comment]
> もし対応した場合は10分放置した後など、環境が落とされた後でも問題ないかを確認した方がよい。

環境がリセットされなければRailsを更新するのが一番だけど果たして...(formをfに置き換えないといけない問題や #405 も影響を受ける事もあって、もしそれができないならcodenvy消した方がいいのでは？とも思ったりしました

**Comment by urimaro** [comment]
@sho-h 
以下の理由からこのissueはcloseしても良さそうに思いましたが、いかがでしょうか？

- ガイドの内容が更新されている(Rails 7.0前提)
- 直近3回のイベント(※)ではcodenvyは使っていない

※ 昨年7月のTokyo、今年4月のTokyo、Nagasakiでは使わなかったと江森さんからお聞きしました

**Comment by urimaro** [comment]
@sho-h 
こちら、いかがでしょうか？

**Comment by hsbt** [comment]
@urimaro @sho-h さんは数年前に他界されてまして、この issue も記載の通りの理由から進展は無いと思うので閉じておきます〜。

**Comment by urimaro** [comment]
@hsbt 
教えていただいて気づきました…
ありがとうございます:bow:

**Comment by hsbt** [comment]
こちらこそ、triage 業ありがとうございます!
