### ISSUE TITLE
携帯でガイドを見た時のoctcatとmenuの位置関係

### ISSUE THREAD

**Issue by sho-h** [railsgirls-jp/railsgirls.jp#408]
octcat かわいいですねー。

ところで携帯で見ると menu の位置がちょっと違和感ある事に気づいたので、menuの方を少し移動してもいいかもしれません。あるいはどっちかを反対側に持っていくとか。

<img width="342" alt="2018-11-14 23 05 06" src="https://user-images.githubusercontent.com/60238/48487609-17e32000-e862-11e8-9974-4b180c1d6308.png">

**Comment by emorima** [comment]
PC版でも、画面幅を少し小さくすると、octcat と☆がかぶってしまったりするので、
確認してみますー。 :octocat:

**Comment by sho-h** [comment]
すみません、お手数ですー。

**Comment by emorima** [comment]
少し下にずらしてみました。

### 修正前
<img width="342" src="https://user-images.githubusercontent.com/458273/48886428-461ebc00-ee6f-11e8-9e1c-fb3972bc0ddc.png">


### 修正後

<img width="342" src="https://user-images.githubusercontent.com/458273/48886436-4ae37000-ee6f-11e8-8661-5e4a3599f35d.png">

**Comment by emorima** [comment]
右側だと調整が難しかったので、バーガーメニューを左に表示して対応済みです！

![image](https://user-images.githubusercontent.com/458273/63207176-54e38800-c0fc-11e9-9521-d9f6819dd2ee.png)
