### ISSUE TITLE
Windows用(Win10 64bit)の環境にWSLのGuideを追加したい

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/railsgirls.jp#418]
Win10 64bit用の場合の環境で、WSL環境にしたいというお話を
@igaiga さんと @okuramasafumi さんと一緒に対応予定です。

* 1/26 開催のKobe 4thの終わった後に対応する
* 1/31(木) Tokyo 11th コーチ素振りまでに対応する
  * Tokyo 11thでうまくいったら、本家へのPRを送る

- [x] 動作検証 (@igaiga)
- [x] ガイドの修正
  - [x] installページの修正
    - [ ] 事前確認として、Windowsのパスワード(PINではない)を確認しておいてもらう
  - [x] appのページの修正
  - [x] herokuのページの修正

**Comment by okuramasafumi** [comment]
https://raw.github.com/railsgirls/installation-scripts/master/rails-install-ubuntu.sh

↑のシェルスクリプトがネイティブなUbuntuでのインストールガイドで用いられているようなのですが、WSLでの流用についてのお考えを伺いたいです。
@emorima @igaiga @shimoju

**Comment by emorima** [comment]
インストールは出来るだけ簡単な方がいいと思いますし、
シェル叩けばOKというのは、エンジニアが楽するためによくやることなので、
流用してもいいと思っています。

ただ、本家のガイドの更新とバージョンを合わせたりする必要があると思います。
2.5.3 のPR出したけど、まだマージされていなかったりするので、
#421 でもお話にあがっていたりするように、日本語版とのガイドをどう追随させていくのか...かと思います...
https://github.com/railsgirls/installation-scripts/pull/51

**Comment by okuramasafumi** [comment]
@emorima ありがとうございます。よくみたら、Rubyのインストールに`rvm`を使っているなど現行のインストール方法とはズレがあるため、そのまま採用は難しそうですね。

**Comment by shimoju** [comment]
@okuramasafumi 
そうですね、rvmだったりNodeも6だったりちょっと古いので、流用するにしても現状のrbenv環境用にスクリプトを作り直して、それをネイティブのUbuntu用としても使う、という形になりそうですね。
ネイティブのUbuntuを使う人は少なそうなので、メンテナンスの省力化という意味でも共通化は良いと思います（コーチと一緒にスクリプトの中身を見てみよう、みたいなコメントをつけるのもいいかと）。

**Comment by okuramasafumi** [comment]
@shimoju `11th`に間に合うかわかりませんが、スクリプトの書き直しはぜひやりたいですね。

**Comment by igaiga** [comment]
@okuramasafumi 提案ありがとうございます！流用するなら現状の最新バージョンで再実装が良いと思います！（たぶんshimojuさんと同じ意見）
ただ大倉さんが書いてるようにスクリプトの書き換え＆追随大変だと思うので、まずは「理想のコマンド群を素直にガイドにべた書き」に1票です。

**Comment by okuramasafumi** [comment]
@igaiga ありがとうございます。
皆さんのご意見を参考にして、まずはコマンドべた書きで、本家の状況を見つつスクリプト化していくことにします！

**Comment by emorima** [comment]
WSLのインストールを、Tokyo11thから何回か行なって、
現時点では特に加筆も不要そうなので、closeします！
