### ISSUE TITLE
railsgirls.jpはrailsgirls.comに追随していくのでしょうか？

### ISSUE THREAD

**Issue by urimaro** [railsgirls-jp/railsgirls.jp#421]
railsgirls.jp(以下jp)には、railsgirls.com(以下com)にないコンテンツが含まれているように思います。
一方、comも更新されていて、jpに取り込まれていないコンテンツが増えています。
今後もjpはcomに追随していくのでしょうか？
追随していく場合、どのようにjpを更新すれば良いでしょうか？
jpオリジナルのコンテンツを踏まえた上で、comの更新内容を取り込んだpull requestを作成する感じでしょうか？

jpのオリジナルはコラム化して、comを翻訳したコンテンツとjpオリジナルのコンテンツが混ざらないようにすると、com -> jp、jp -> comがやりやすのかもと思いました。

**Comment by hsbt** [comment]
最近、本家への追従があまりできてないんですが、乖離を続けて独自進化していくのは OSS っぽくない(jp は fork ではない)ので、出来るだけ揃えたい、という気持ちです。

> jpのオリジナルはコラム化して、comを翻訳したコンテンツとjpオリジナルのコンテンツが混ざらないようにすると、com -> jp、jp -> comがやりやすのかもと思いました。

上記良さそうです! 「独自コンテンツ」ということでフォルダを分けるなどするだけでもやりやすさが変わるかもしれません。

**Comment by okuramasafumi** [comment]
現在インストールガイドの修正をしているのですが、本家の方を見るとRubyのバージョンがかなり古かったりしていて（まだ`2.4`系を使っている）、むしろこちらから本家にPull Requestを送ることを考えてもいいのかなと思いました。

**Comment by hsbt** [comment]
本家の方も有志が頑張る、という状態なので本家を最初に直してしまう、というのはありだと思います!(僕もマージできるんで、継続的にメンテナンスしていただけるようならコミット権配布します。)

**Comment by igaiga** [comment]
私もRuby2.2, Rails5.1の頃( https://github.com/railsgirls/railsgirls.github.io/pull/296 )までは本家を直してPR送ってたので、今後も本家にPR送ってupdateしていきたい所存です。（それ以降は執筆などで疲れていて手を動かせてませんでした・・・。なので本家進める方もやってくださる方いましたらサポートします。）

**Comment by hsbt** [comment]
https://github.com/railsgirls-jp/railsgirls.jp/pull/607 でエイヤッと追従しました。ファイル構成もほぼ踏襲しています。
