### ISSUE TITLE
c9 のアカデミックプランの代替策の検討

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#449]
----

On April 2, 2019 we announced that we plan to discontinue the ability to
create new or to use existing workspaces on c9.io on June 30, 2019 and to
discontinue all access to c9.io on December 31, 2019.

----

というメールが来て、今、Windows ユーザーが workshop をやるときに使っている c9 が終わってしまうそうです。

というわけで、Windows を所有しているユーザー向けにどう開発のチュートリアルを体験してもらうか、ってのを考えましょう。

**Comment by igaiga** [comment]
Windowsユーザーのメイン環境をWSLにするに1票です。問題点としては、Windows10でないと使えないこと、インストールデイの環境構築に時間がかかること、です。実績は前回のTokyo11開催で5人？ほど利用して前述以外の問題はなかったです。

TokyoではWSLがダメなときの保険としてc9を使っていたので、そこにはまる新しい何かがあるといいなと思ってます。そしてWSL環境構築速度改善は長期的にはWSL2に期待かなぁ。

**Comment by emorima** [comment]
アカウント作成済みの方にご連絡して、サービスが終了する旨の連絡をしておきます。

**Comment by hsbt** [comment]
あ、一応終了、というわけではなくて AWS に買収されちゃいましたという感じなので、「フリープランが終わったので〜」という書き味でお願いします〜

**Comment by emorima** [comment]
書き味、了解です！

**Comment by hsbt** [comment]
環境は codespaces 、デプロイ先は heroku team を期間限定で使えばよかろうという感じにした。
