### ISSUE TITLE
Rails6へGuideを対応する

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/railsgirls.jp#465]
Rails6 へのGuide対応を行う

日本語訳されているGuideは以下。

- [ ] インストール(/install)
- [ ] アプリ(/app)
- [ ] コメント(/commenting)
- [ ] デザイン(/design)
- [ ] サムネイル(/thumbnails)
- [ ] 認証(/devise)
- [ ] プロフィール(/gravatar)
- [ ] デザイン2(/design-html-css)

**Comment by emorima** [comment]
- [ ] Mac @okuramasafumi さん
- [ ] RubyInstaller @igaiga さん
- [ ] WSL @emorima 

インストール、アプリ作成、デプロイまでを Okinawa2nd までに対応する

**Comment by cobachie** [comment]
Mac 環境で以下のページを確認して、  
mini_magickのバージョンが古かったので、#469 で修正PRだしました。
他はざっと見た感じ大丈夫そうでしたー

- /app
- /commenting
- /design
- /thumbnails
- /devise
- /gravatar
- /design-html-css

**Comment by igaiga** [comment]
こばちえさん確認ありがとうございますー！！！ 🌟

**Comment by urimaro** [comment]
2023-06-04現在、Rails 7.0.4.2 以上 でガイドが作られているので、このissueはcloseします:pray:
