### ISSUE TITLE
/guide TryRubyのリンクを更新する

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/railsgirls.jp#490]
本家の以下のPRをJPへ反映させる
https://github.com/railsgirls/railsgirls.github.io/pull/401/files

**Comment by urimaro** [comment]
現在、TryRubyのURLは https://try.ruby-lang.org/ に変わっています
また、コード中のリンクはすべて変更後のURLが設定されているようなので、このissueはcloseしますね

**Comment by urimaro** [comment]
> また、コード中のリンクはすべて変更後のURLが設定されているようなので

すみません:bow:
修正できていないページがあったので、修正できてから、このissueをcloseするようにします
