### ISSUE TITLE
/app ページを本家にあわせる

### ISSUE THREAD

**Issue by cobachie** [railsgirls-jp/railsgirls.jp#491]
本家ガイドでは、/app ページに tip が追加されたり、code の表示が変わっていたりしているので、
JPガイドも本家サイトにあわせて更新する。

- [本家](https://github.com/railsgirls/railsgirls.github.io/blob/master/_posts/2012-04-18-app.markdown)
- [JP](https://github.com/railsgirls-jp/railsgirls-jp.github.io/blob/master/_posts/2012-04-18-app.markdown)

**Comment by urimaro** [comment]
2023-06-04現在、本家のガイドに追随しているので、このissueはcloseしますね🙏

**Comment by hsbt** [comment]
👍
