### ISSUE TITLE
推奨テキストエディタをAtomからVS Codeにしたい

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/railsgirls.jp#493]
Title通りです

**Comment by okuramasafumi** [comment]
賛成です。
参考までに、両者のコード変更量へのリンクを貼っておきます。

https://github.com/atom/atom/graphs/code-frequency
https://github.com/microsoft/vscode/graphs/code-frequency

明らかにVSCodeのほうが開発の進みが速いので、それをどうみるかですね（見方によっては、Atomのほうが安定しているとも言える）。

**Comment by yada-ITA** [comment]
この案に+１、だったので、推奨エディタを変更してみたものを書いてみました。（#508）

**Comment by hsbt** [comment]
https://railsgirls.jp/tools で vscode になりました。codespaces も両軸で紹介していくのが良さそうに見える。
