### ISSUE TITLE
/deviseのガイドの中のrubyコードやHTMLタグのclass名などが英語と日本語で少し違う

### ISSUE THREAD

**Issue by morinoko** [railsgirls-jp/railsgirls.jp#495]
微妙に違うところをリストアップします：

- devise gem を追加
  - 英語：`bundle install` 
  - 日本語：`bundle`
- アプリに devise をセットアップ
  - 英語：`rails g devise:install` 
  - 日本語：`rails generate devise:install`
- Devise の環境設定
  - 英語：`config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }` 
  - 日本語：`config.action_mailer.default_url_options = { host: 'localhost:3000' }`
- User model をセットアップ
  - 英語：`rails g devise user` 
  - 日本語：`rails generate devise user`
- サインアップとログインリンクの追加 (HTML)
  - ①
    - 英語：`<p class="navbar-text float-right">` 
    - 日本語：`<p class="navbar-text pull-right">`
  - ②
    - 英語：`<ul class="navbar-nav mr-auto">` 
    - 日本語：`<ul class="nav navbar-nav">`

**Comment by urimaro** [comment]
2023-06-05現在、まだ本家に追随できていませんでした
また、以下の問題もあるようです

- #599 

本家もこの対応が必要そうです
