### ISSUE TITLE
guides.railsgirls.com を見てそのまま翻訳できそうか雑に見てみた

### ISSUE THREAD

**Issue by igaiga** [railsgirls-jp/railsgirls.jp#496]
http://guides.railsgirls.com/

目次

Guide 1: Guide to install Rails (Current page!)
Guide 2: Build Your First App
Guide 3: Push Your App to GitHub
Guide 4: Put your app online with…
⬆️チェックしてない
⬇️ここから英語版のガイドがそのまま使えそうか見ている
Guide 5: Allow Comments on Your App 最新ぽい
Guide 6: Add design using HTML & CSS 判別できなかった（デザインわからない）
Guide 7: Create thumbnails with Carrierwave 最新ぽい（ActiveStorageにしたいという野望はあるかも）
Guide 8: Add Authentication (user accounts) with Devise 動かしてみないと分からない
Guide 9: Add Profile Pics with Gravatar 動かしてみないと分からない（gravaterはまだサービスやってるようだ）
Guide 10: Improve your design with HTML and CSS 最新ぽい
Guide 11: Continuous Deployment
Test your app with RSpec rspec-railsのバージョンが古い、翻訳優先度:高
Simplifying your tests with Shoulda Matchers 翻訳優先度: 低
CD with Travis-CI: 翻訳優先度: 低？
CD with Codeship: 翻訳優先度: 低
Guide 12: Build a voting app in Sinatra 最新ぽい 翻訳優先度:高
Guide 13: Build a diary app in Ruby on Rails たぶん古い 翻訳優先度:中？
Guide 14: Add a back-end to your app (admin pages) 動かしてみないとわからない 翻訳優先度:低

**Comment by urimaro** [comment]
2023-06-06現在、.comの構成が変わっているので、このissueはcloseしますね:pray:

**Comment by hsbt** [comment]
👍
