### ISSUE TITLE
2019 の会計報告をエントリとして出す

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#503]
@hsbt @springaki @emorima で進行中です。

8割くらいイベントの決算と通帳の照会を終えましたが、通帳の明細で二つの期間が合算されて省略されてしまったので銀行に明細を照会中です。1/20 の週に届く予定なので到着後、1月中に出せるように進めます。

**Comment by emorima** [comment]
こちら blogで公開したのでcloseします。
https://railsgirls.jp/2020/01/29/2020-overview/

@hsbt ありがとうございました！
