### ISSUE TITLE
Chrome でイベントページの画像が表示されていないので対応する

### ISSUE THREAD

**Issue by emorima** [railsgirls-jp/railsgirls.jp#529]
Chrome で [イベントページ](https://railsgirls.jp/events/) を表示すると、
イベントの画像が本家(http)サイトにあるため、Mixed contentで表示されていない

JPサイトに画像をもってきて、ローカルの画像を表示するように対応する

**Comment by amatsuda** [comment]
JPサイトに画像をもってきて、よりは、本家をHTTPSにも対応してもらうほうが本筋な気がしますね。
とりあえず気づいちゃった人が railsgirls/railsgirls にissueをいっちょ投げてみるぐらいでどうでしょうか？

**Comment by emorima** [comment]
そうですね、issue投げて様子みようと思います。

**Comment by emorima** [comment]
https://github.com/railsgirls/railsgirls/issues/2093

**Comment by urimaro** [comment]
紆余曲折ありましたが(※)、表示できるようになったので、このissueはcloseします:pray:

※ 柴田さん(@hsbt)ありがとうございました(お疲れ様でした)
