### ISSUE TITLE
heroku が無料プランではなくなるので代替サービス/体験を考える

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#571]
クレカなしでグローバルに公開できて、Web アプリケーションを作った!と感じれるような Rails のデプロイ先が欲しい。

**Comment by neko314** [comment]
オフィシャルな情報ではないのですが、Herokuからの代替になるサービス一覧があったので貼ってみます。
https://github.com/DmitryScaletta/free-heroku-alternatives

他にはsupabaseというサービスがあるようです。料金ページ貼ります。
https://supabase.com/pricing


探せば他にもあるかもしれないです。

トータルするとRenderがいいという話をどこかでみたんですが忘れました 💭 


----
これらは「クレカなしでグローバルに公開できて、Web アプリケーションを作った!と感じれるような Rails のデプロイ先」だろうか🤔

**Comment by komagata** [comment]
supabase好きで使っているんですが、基本DBの提供でWebページやサーバーサイドプログラムをホストする機能はないのでRailsGirlsの文脈でHerokuの代わりにはならないかもです。

僕の周囲ではRenderやFly.ioをよく聞きます。

**Comment by okuramasafumi** [comment]
https://dokku.com/
いっそPaaSではなく、自前でDokkuをホストしてしまうという手もありそう…（必要な機能はGitのプッシュとビルドと公開URLだけだと思うので）
ただ、サーバーの管理という大問題がありますが…
https://marketplace.digitalocean.com/apps/dokku?refcode=fe06b043a083
DitigalOceanならクリックだけでインストールはできるよう。

**Comment by komagata** [comment]
ジャストアイデアですが、もし可能であれば、弊社のフィヨルドブートキャンプで「サーバースポンサー」みたいな形でDokkuの管理と料金をスポンサードさせていただくなどという形が取れれば面白いかな〜と思いました。

**Comment by amatsuda** [comment]
なんか、なぜRails Gilrsっていう活動にとってHerokuがその他のPaaSと違って特別な存在なのかというと、Rails Girlsそのものの立ち上げメンバーであるTerenceとか、この前RubyコミッターになったRichardとか、もう辞めちゃったけどあのデカ外人とか、ああいう人たちが在籍していて、コミュニティと繋がってるからなわけですよね。そういう観点を抜きにして単にタダで使えるかどうかって話に終始して、その結果、誰が作ってるのかもわからんようなサービスに全乗りするような結論になっちゃったりしたら残念だなぁ、と懸念を表明しておきます(個人的にはRenderあたりはめっちゃプロダクションで使ってたりはするんだけど、それはそれ)。

で、じゃあ何か建設的な意見はあんのか？って言われそうなところですが、皆さんRichardが何か仕掛けようとしてるのは目に入ってますかね？とりあえずRails Girls JP方面からもこれに反応しておくといいんじゃないかと思うし、おのおの個人的に思うところを表明してみたりして1票を投じてみると、彼の後押しになるかもしれません。

https://twitter.com/schneems/status/1570459932461342722

**Comment by emorima** [comment]
Tokyo 15th, Nagasaki 1st開催が近くなってきているので、
現状をこちらに記載しておきます。

Rails Girls Japanで、Heroku Teamsの申し込みをしました。
25名まで $10/月で利用できる契約です。
https://jp.heroku.com/team-administration

ひとまずこちらで対応しておきつつ、様子をみようと思います。

### コーチ素振り時

* コーチ素振りの時にRails Girls Japan Teamにmemberとしてinviteします。(adminの @hsbt と @emorima でやる )
* 素振りでコーチに、メールが届いてから、アプリデプロイまでのフローをご確認頂きます。

### コーチ素振り後

* インストールデイ前に素振りの時にコーチが作成したアプリの削除と、コーチをmemberから外します。( @emorima でやる )
⇒Tokyo以外の参加者・コーチであれば数的に大丈夫なので、そのままにしておくかもです。

### インストールデイ（またはワークショップ当日）

* 参加者の方にrailsgirls-jp のslackに入ってもらい、slackで @emorima にメールアドレスの連絡をしてもらいます。
* 確認した @emorima が招待メールを送り、slackでお返事します。
  * 漏れなくinviteしているかどうかの確認のため、返事を送るようにします。
* ワークショップでmemberアカウントでアプリをdeployしてもらう。

### ワークショップ後

* 一定期間でアプリの削除とmemberを外します。( @emorima でやる )
  * 1か月くらいは残しておきたいと思いますが、今回のTokyo 15thと Nagasaki 1stが１週間なので、１週間かもしれないです。

### その他

* 参加者の方がherokuで自分で支払いするので、作ったアプリを自分のアカウントに移行したい希望などあった場合、アプリとmemberが残っていれば、対応可能です。

**Comment by hsbt** [comment]
わかってる人が自分で heroku の支払いなどをやりますとかなら app の transfer はできます、ってのを最後に追加するといいかなあ。

**Comment by emorima** [comment]
その他で追記しました！

**Comment by hsbt** [comment]
ノウハウを guide に書いたら閉じる

**Comment by hsbt** [comment]
guide にまだ書いてなかった

**Comment by hsbt** [comment]
https://github.com/railsgirls-jp/railsgirls.jp/commit/10bb460f03fe05a98765ac9705253fb210400cc8 に書いてみました。もうちょい開催手順を文章にしたいですね...
