### ISSUE TITLE
年間スポンサーのヘイ株式会社様が「STORES株式会社」に社名変更になったのでスポンサー情報も更新する

### ISSUE THREAD

**Issue by neko314** [railsgirls-jp/railsgirls.jp#574]
プレスリリースはこれかな。https://netkeizai.com/articles/detail/7141

ロゴも変わっているようなので、年間スポンサーのページの社名とロゴを変更する必要がありそうです。

**Comment by neko314** [comment]
誰か個人がシュッとインターネットで情報を取ってきて変更するのではなくRG Japanとして会社と連絡をしてから対応する。（[そういう趣旨のSlackポスト](https://railsgirlsjp.slack.com/archives/CEHP2DG4Q/p1664680375509469?thread_ts=1664680219.414329&cid=CEHP2DG4Q)）

ご対応よろしくお願いします 🙏

**Comment by neko314** [comment]
https://github.com/railsgirls-jp/railsgirls-jp.github.io/pull/575 がマージされたのでクローズします

**Comment by hsbt** [comment]
reminder ありがとうございました!
