### ISSUE TITLE
Deviseの説明をRails 7.0に対応させる

### ISSUE THREAD

**Issue by JunichiIto** [railsgirls-jp/railsgirls.jp#599]
https://railsgirls.jp/devise の内容ですが、Rails 7.0でHotwire/Turboを使っているとうまく動かない箇所があります。
具体的には以下の点です。

```diff
-<%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
+<%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'navbar-link'  %>
```

Rails 7.0の使用を前提としている場合は記述を見直した方がいいかもしれません。

参考

- https://github.com/heartcombo/devise/wiki/How-To:-Upgrade-to-Devise-4.9.0-%5BHotwire-Turbo-integration%5D#data-method-vs-data-turbo-method / [日本語訳](https://gist.github.com/JunichiIto/1398835b9825a9ce3958456041f59d27#data-method-%E3%81%A8-data-turbo-method)
- 修正対象のファイルは[これ？](https://github.com/railsgirls-jp/railsgirls-jp.github.io/blob/master/_posts/2012-11-01-devise.markdown)

**Comment by maimux2x** [comment]
こちら自分の方で本家含め確認してみます！
