### ISSUE TITLE
「Test your app with RSpec」を翻訳します

### ISSUE THREAD

**Issue by inoue-ryoki** [railsgirls-jp/railsgirls.jp#672]
https://railsgirls.jp/testing-rspec
を翻訳してみます

**Comment by kaosf** [comment]
@inoue-ryoki <del>リンクちょっと間違ってるので修正しておくと良いと思います https://railsgirls.jp/testing-rspec</del> 修正済

**Comment by kaosf** [comment]
@inoue-ryoki あっ！この人の issue https://github.com/railsgirls-jp/railsgirls.jp/issues/322 とダブってしまってるみたい…こちらに行って協業の相談をするか，他の所を探した方が良いかも…

**Comment by inoue-ryoki** [comment]
@kaosf 
このissue作られたの、すごい前だから大丈夫かなと思ったのですが。

**Comment by kaosf** [comment]
@maimux2x ↑との流れなのですが，こちら @inoue-ryoki さんがやってしまっても問題ないでしょうか？お手数ですがご確認頂けると幸いです．

※inoue-ryokiさんは私の知り合いで今Rubyの勉強を私がサポート中で横から色々コメントしてる…という状況です．

**Comment by maimux2x** [comment]
@kaosf 
ご連絡ありがとうございます。
#322 はcloseいただくように自分から確認いたします。
そのため、本issueにて翻訳のご対応をお願いできますと幸いです🙏

**Comment by kaosf** [comment]
@inoue-ryoki とのことです

Good Luck!

**Comment by inoue-ryoki** [comment]
@maimux2x 
ご確認ありがとうございました。

**Comment by inoue-ryoki** [comment]
@maimux2x 
プルリクエスト送ったので、ご確認よろしくお願いいたします
