### ISSUE TITLE
guides.js の翻訳

### ISSUE THREAD

**Issue by cafedomancer** [railsgirls-jp/railsgirls.jp#681]

**Comment by cafedomancer** [comment]
JavaScript のファイルは ja でディレクトリが切られているものもあるようなのですが、以下のどちらのファイルを翻訳すべきでしょうか？ 現状は ja なしのほうが動いているようです。

- `js/guides.js`
- `js/ja/guides.js`

**Comment by maimux2x** [comment]
@cafedomancer 
https://github.com/railsgirls-jp/railsgirls.jp/pull/615/files
こちらのPRで暫定的に作成した `js/ja/guides.js` が 反映されていないようです。

@hsbt 
JSのファイルについてですが、こちらも`ja` ディレクトリは切らずに直接 `js/guides.js` を修正する形で進めて良いでしょうか？何か懸念などがありましたら、お知らせいただけると幸いです🙏

**Comment by hsbt** [comment]
>こちらのPRで暫定的に作成した js/ja/guides.js が 反映されていないようです。

これは僕の作業ミスですね...

>こちらもja ディレクトリは切らずに直接 js/guides.js を修正する形で進めて良いでしょうか？

それでいきましょう!

@cafedomancer `js/ja/guides.js` を `js/guides.js` にマージ、もし未翻訳があれば翻訳、という2つを対応してもらえるとありがたいです 🙏

**Comment by cafedomancer** [comment]
> @cafedomancer `js/ja/guides.js` を `js/guides.js` にマージ、もし未翻訳があれば翻訳、という2つを対応してもらえるとありがたいです 🙏

分かりました！
