### ISSUE TITLE
「Rails Girls インストール・レシピ」に原文が混じっている

### ISSUE THREAD

**Issue by cafedomancer** [railsgirls-jp/railsgirls.jp#682]
https://github.com/railsgirls-jp/railsgirls.jp/blob/c745f14cb3269021c71866e05626b59288ffaf6f/_pages/install.md#L35
https://github.com/railsgirls-jp/railsgirls.jp/blob/c745f14cb3269021c71866e05626b59288ffaf6f/_pages/install.md#L104

**Comment by urimaro** [comment]
以下のPRで対応したのでcloseしますね

- #657
