### ISSUE TITLE
「Linux 用セットアップ」　を翻訳します。

### ISSUE THREAD

**Issue by kyokucho1989** [railsgirls-jp/railsgirls.jp#686]
_pages/install/linux.md　を翻訳します。

**Comment by urimaro** [comment]
@kyokucho1989 
お伝えするのを忘れていました:bow:
以下のページのように翻訳者として、ご自身の情報を追加することもできます
抵抗がないのであれば、ぜひPRを作成してください:pray:

- https://railsgirls.jp/html-and-css

**Comment by kyokucho1989** [comment]
追加しました。お願いします。
