### ISSUE TITLE
Track https://github.com/railsgirls/guides.railsgirls.com/pull/519 changes

### ISSUE THREAD

**Issue by hsbt** [railsgirls-jp/railsgirls.jp#687]
https://github.com/railsgirls/guides.railsgirls.com/pull/519 の変更をこのリポジトリに反映させる。

以前から .com で更新された内容を反映させるには diff を人間が確認して、センテンスごとに切り貼りをしてコミット、その後翻訳というフローをしているので、まずはセンテンスの切り貼りをやる(もしくは誰かやってほしい...)。

この辺、毎回追いつかなくて差分が大きくなる、というのを繰り返しているのでなにかいい方法があったら採用したい。

**Comment by sontixyou** [comment]
@hsbt 
このIssueは、すでに着手されていますか？

もし、着手前でしたら、私がこのIssue対応したいです。

**Comment by hsbt** [comment]
何もやってないのでお願いします!

**Comment by sontixyou** [comment]
## TODO

チェックボックス1つで1PRを作成する粒度で進めていきます。

- [x] [英文側のPR](https://github.com/railsgirls/guides.railsgirls.com/pull/519)を英文のまま、こちらのレポジトリに取り込む
- [x] 取り込んだ英文を翻訳

**Comment by urimaro** [comment]
> 毎回追いつかなくて差分が大きくなる、というのを繰り返しているのでなにかいい方法があったら採用したい

悩ましいですよね

1. 日本語用のサブディレクトリを作る  
    .comの変更は取り込みやすい反面、「どの状態まで翻訳したのか」は管理しないといけない
1. .comでPRがmergeされたら、mergeされたPRと同じPRを自動で作る  
    作られるPRは日本語を英語で置き換えるものになるが、そのPRを更新する形で翻訳する  
    .comがどのように変更されたのかがわかりにくそう

.comの変更点がわかりやすいのであれば「2」が良さそうかなと思いました
「PRの作り方次第」なんでしょうか…

**Comment by urimaro** [comment]
以下のタスクが完了しているので、このissueはcloseしますね:pray:

- [英文側のPR](https://github.com/railsgirls/guides.railsgirls.com/pull/519)を英文のまま、こちらのレポジトリに取り込む
- 取り込んだ英文を翻訳

**Comment by hsbt** [comment]
👍 当面は .com の取り込みは英文で入れる、翻訳をする、の2段階にしつつ、一緒にできるならする、くらいでいきましょう〜
