### ISSUE TITLE
「Continuous Deployment with Travis」を翻訳する

### ISSUE THREAD

**Issue by maimux2x** [railsgirls-jp/railsgirls.jp#744]
https://railsgirls.jp/continuous-travis
上記ページを翻訳する。

**Comment by maimux2x** [comment]
monyatto さん担当

**Comment by monyatto** [comment]
@maimux2x 
アサインお願いします〜🙏

**Comment by maimux2x** [comment]
@monyatto 
アサインしました✨よろしくお願いします〜！

**Comment by maimux2x** [comment]
@monyatto 
こちら対応状況はいかがでしょうか？
急いで欲しい意図は全くないのでご心配無用です🙏
もし詰まっているなどあればフォローも可能なため状況だけ確認させていただけると幸いです〜！

**Comment by monyatto** [comment]
@maimux2x 
お待たせしております🙇🏻
こちら少しずつ進めており、来週中には一旦終えられるかと思います〜🙏
