### ISSUE TITLE
「Continuous Deployment with the Codeship」を翻訳する

### ISSUE THREAD

**Issue by maimux2x** [railsgirls-jp/railsgirls.jp#745]
https://railsgirls.jp/continuous
上記ページを翻訳する。

**Comment by maimux2x** [comment]
peno022 さん担当

**Comment by peno022** [comment]
@maimux2x こちら担当します！よろしくお願いします。
（※memo 新規メンバーはissueにコメント等なにかアクションしないとアサインができない）
