### ISSUE TITLE
ファイルを生成するrakeタスクとその出力先の関係がわかりにくい

### ISSUE THREAD

**Issue by urimaro** [railsgirls-jp/railsgirls.jp#750]
`post` は `_posts` に出力せず、`blog` が `_posts` に出力するため、ファイルを生成するrakeタスクとその出力先の関係がわかりにくいです

| コマンド | 説明 | 出力先 |
|--------|--------|--------|
| `rake post` | 訳文用のファイルを生成する | `_pages` |
| `rake blog` | ブログ用のファイルを生成する | `_posts` |

以下のように変更するとわかりやすくなるかもしれません

- 訳文のファイルを出力するコマンドを変更する  
    `rake post` を `rake page` や `rake create_page` といったコマンドに変える
- ブログの出力先( `rake blog` の出力先)を変える  
    `_posts` をやめて他のディレクトリに出力する

※ どちらか一方でも十分だと思います

**Comment by maimux2x** [comment]
https://github.com/railsgirls-jp/railsgirls.jp/pull/608
こちらに
> blog は jekyll の都合で _posts に置く
とコメントがあるため、訳文のファイルを出力するコマンドを修正する方向で検討します。

**Comment by maimux2x** [comment]
訳文を出力するコマンドを `rake guide` に変更するのはどうかと考えているのですが、いかがでしょうか？
独自ページの作成で `rake page` を実行するため、そこと混ざらないようにという意図もあります。

**Comment by urimaro** [comment]
> 訳文を出力するコマンドを rake guide に変更するのはどうかと考えている

良いと思います

> 独自ページの作成で rake page を実行するため

日本語版の独自コンテンツは `_pages-jp` に格納しているようなので、`rake page` の `desc` でその旨を説明したりしても良いかもしれませんね

**Comment by maimux2x** [comment]
@urimaro 
ありがとうございます！
修正してPRを出すようにします〜✨

**Comment by maimux2x** [comment]
こちら修正するためにコマンドの確認をしていたのですが、独自コンテンツは２パターンあって
一つは

- `_pages-jp` 配下にファイルが作成され、`https://railsgirls.jp/piyo`

になるパターン
こちらは現状ファイルを自動生成するコマンドがないため新規追加しても良さそうです。

もう一つは

- `events` ディレクトリのようにディレクトリが存在しその中でファイルを管理するパターン
  - `https://railsgirls.jp/events/` のようなリンクになる 

これが
`$ bundle exec rake page name="something"`
の方に対応しています。

対応内容を整理して、こちらにコメントするか新たにissueを追加するようにします。

**Comment by maimux2x** [comment]
#755 でRakefileの内容とREADMEを修正してみました。
コマンド名と説明についてフィードバックをいただけると幸いです🙏🏻
