### ISSUE TITLE
英文が残っている箇所

### ISSUE THREAD

**Issue by maimux2x** [railsgirls-jp/railsgirls.jp#764]
- [x] _includes/main_guides.md  
    #766 
- [x] _pages/guide-to-the-guide.md
    #775 
- [x] _pages/remote-pairing-for-the-win.md  
    #772 
- [x] index.html  
    #768 
- [x] _layouts/guide.md  
    #770

**Comment by urimaro** [comment]
すべてmergeされたのでcloseします :clap::tada:
