### ISSUE TITLE
guide が iPhone の Safari で見ると responsive に表示されない

### ISSUE THREAD

**Issue by takkanm** [railsgirls-jp/railsgirls.jp#81]
iPhone の Safari で見ると本家では発生しない横スクロールが発生します。

原因としては、今の本家で使われていない 960.css が使われていることが問題のように見えます。
試しに 960.css を外したところ、以下の問題が発生しましたが、ほとんどのコンテンツが画面に収まりました。
- 若干マージンかパディングがはみ出る
- 本家にない `nav` 要素がはみ出る

**Comment by urimaro** [comment]
今は再現しないようなので、このissueはcloseします

以下、iPhone 8 + Safari でのスクリーンショットです
横スクロールは発生しませんでした
また、「日本で近日開催のイベント」は良い感じに配置されていました

![image1](https://github.com/railsgirls-jp/railsgirls.jp/assets/752746/98262a77-0a28-4fb8-90ad-ea07db7b2579)

![image2](https://github.com/railsgirls-jp/railsgirls.jp/assets/752746/d997317a-8312-43b6-bb9b-f25d84c1f904)
